CREATE TABLE cars (
id  integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
make VARCHAR (25) NOT NULL,
model VARCHAR (25) NOT NULL,
year integer,
color VARCHAR (15) NOT NULL,
engine VARCHAR (10) NOT NULL,
descr VARCHAR (1500) NOT NULL,
price integer);


INSERT INTO cars
(make, model, year, color, engine, descr, price)
VALUES
('BMW', 'Garmisch', 1970, 'Gold', '3L I6', 'Lorem Ipsum', 500.000);



ALTER TABLE cars
  ADD COLUMN quantity integer constraint;
)